# Generated by Django 4.1.7 on 2024-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
