# Generated by Django 4.1.7 on 2024-04-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_has_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_unread_messages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unread_messages',
        ),
    ]
