# Generated by Django 4.1.7 on 2024-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_login_otp_user_login_otp_used_user_otp_base32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_active',
            field=models.BooleanField(default=False),
        ),
    ]
