# Generated by Django 4.1.7 on 2024-05-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_otp_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_otp_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
