# Generated by Django 4.1.7 on 2024-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('credentials', 'credentials'), ('google', 'Google')], default='credentials', max_length=30),
        ),
    ]
