# Generated by Django 4.1.7 on 2024-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_registration_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_method',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
