# Generated by Django 4.1.7 on 2024-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_has_oauth_credentials_oauthcredential'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthcredential',
            old_name='token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='oauthcredential',
            old_name='uid',
            new_name='refresh_token',
        ),
    ]
