# Generated by Django 4.1.7 on 2024-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_oauthcredential_user_oauth_uid_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
