# Generated by Django 4.1.7 on 2024-10-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_s_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthcredential',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='oauthcredential',
            name='refresh_token',
        ),
    ]
