# Generated by Django 4.1.7 on 2024-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_oauthcredential_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=400),
        ),
    ]
