# Generated by Django 4.1.7 on 2024-11-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_user_loses_user_wins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loses',
            new_name='losses',
        ),
    ]
