# Generated by Django 4.1.7 on 2024-06-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_game_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final', to='game.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='semi1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semi1', to='game.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='semi2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semi2', to='game.game'),
        ),
    ]
