# Generated by Django 4.1.7 on 2024-11-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_tournament_tournament_final_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
